name: Release 22

on:
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: "Node.js v22.20.0"
        required: true

env:
  LIBNODE_NODE_VERSION: ${{ github.event.inputs.nodeVersion }}

jobs:
  build:
    if: false
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, windows-2022, ubuntu-22.04]
        x64: [0, 1]
        small_icu: [0, 1]
        exclude:
          - os: ubuntu-22.04
            x64: 0
    runs-on: ${{ matrix.os }}
    env:
      LIBNODE_X64: ${{ matrix.x64 }}
      LIBNODE_SMALL_ICU: ${{ matrix.small_icu }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install nasm on Windows
        run: choco install -y nasm
        if: runner.os == 'Windows'

      - name: Install GNU patch on Windows
        run: choco install -y patch
        if: runner.os == 'Windows'

      - name: Install Rosetta (when x64) and ninja on macOS
        if: runner.os == 'macOS'
        run: |
          if [ "${{ matrix.x64 }}" = "1" ] && [[ "$(uname -m)" == "arm64" ]]; then
            sudo softwareupdate --install-rosetta --agree-to-license || true
          fi
          HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja

      - name: Install ninja on Ubuntu
        run: sudo apt-get install -y ninja-build
        if: runner.os == 'Linux'

      - name: Download source code of Node.js
        run: python -m scripts.download

      - name: Build
        run: |
          python -m scripts.build

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Postprocess
        run: python -m scripts.postproc

      - name: Archive
        run: |
          zipname=$(python -m scripts.archive)
          echo "::set-output name=zipname::$zipname"
        shell: bash
        id: archive

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.archive.outputs.zipname }}
          path: ${{ steps.archive.outputs.zipname }}

  build-android-arm54:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          unzip -q NDK
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          bash ./bash/android-static.sh "${LIBNODE_NODE_VERSION}" arm64
      - uses: actions/upload-artifact@v4
        with:
          name: libnode-${{ env.LIBNODE_NODE_VERSION }}-android-arm64.zip
          path: ~/libnode-Android/arm64/

  release:
    if: false
    needs: [build, build-android-arm54]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: .
          merge-multiple: true

      - name: Download Node headers
        shell: bash
        run: |
          TARBALL="node-${LIBNODE_NODE_VERSION}-headers.tar.gz"
          URL="https://nodejs.org/dist/${LIBNODE_NODE_VERSION}/${TARBALL}"

          echo "Downloading: ${URL}"
          curl -fsSL -o "${TARBALL}" "${URL}"
          tar -xzf "${TARBALL}"

          EXTRACT_DIR="node-${LIBNODE_NODE_VERSION}"
          INCLUDE_NODE_DIR="${EXTRACT_DIR}/include/node"

          if [ ! -d "${INCLUDE_NODE_DIR}" ]; then
            echo "Include directory not found at ${INCLUDE_NODE_DIR}"
            exit 1
          fi

          (
            cd "${INCLUDE_NODE_DIR}" || exit 1
            zip -r ../../../include.zip .
          )

          echo "Created include.zip"

      - name: Create combined zip file
        run: |
          zip -r "libnode_${LIBNODE_NODE_VERSION}_all.zip" ./*.zip

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.LIBNODE_NODE_VERSION }}
          release_name: ${{ env.LIBNODE_NODE_VERSION }}
          body: "Automated build for ${{ env.LIBNODE_NODE_VERSION }}"

      - name: Upload release assets
        uses: csexton/release-asset-action@v2
        with:
          pattern: "*.zip"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
