name: Release 22

on:
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: "Node.js v22.20.0"
        required: true

env:
  LIBNODE_NODE_VERSION: ${{ github.event.inputs.nodeVersion }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, windows-2022, ubuntu-22.04]
        x86: [0, 1]
        small_icu: [0, 1]
        exclude:
          - os: macos-15
            x86: 1
          - os: ubuntu-22.04
            x86: 1
    runs-on: ${{ matrix.os }}
    env:
      LIBNODE_X86: ${{ matrix.x86 }}
      LIBNODE_SMALL_ICU: ${{ matrix.small_icu }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install nasm on Windows
        run: choco install -y nasm
        if: runner.os == 'Windows'

      - name: Install GNU patch on Windows
        run: choco install -y patch
        if: runner.os == 'Windows'

      - name: Install ninja on macOS
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
        if: runner.os == 'macOS'

      - name: Install ninja on Ubuntu
        run: sudo apt-get install -y ninja-build
        if: runner.os == 'Linux'

      - name: Download source code of Node.js
        run: python -m scripts.download

      - name: Build
        run: |
          python -m scripts22.build

      # - name: Copy headers
      #   run: python -m scripts.headers

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Postprocess
        run: python -m scripts.postproc

      - name: Archive
        run: |
          zipname=$(python -m scripts.archive)
          echo "::set-output name=zipname::$zipname"
        shell: bash
        id: archive

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.archive.outputs.zipname }}
          path: ${{ steps.archive.outputs.zipname }}

      - name: Test
        run: python -m scripts.test

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: .
          merge-multiple: true
      - name: Create combined zip file
        run: |
          zip -r libnode.zip ./*.zip
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.LIBNODE_NODE_VERSION }}
          release_name: ${{ env.LIBNODE_NODE_VERSION }}
          body: "Automated build for ${{ env.LIBNODE_NODE_VERSION }}"
      - name: Upload release assets
        uses: csexton/release-asset-action@v2
        with:
          pattern: "*.zip"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
